title: Flow Trending
author: flowtrending.com
email: support@flowtrending.com
description: >-
  Flow Trending (FT) is Information Technology company. 
  We develops, manufactures, licenses, supports and sells computer software, consumer electronics, personal computers, and related services.
  Our products is best known software products are the Maketing system for social network suck as ConnectPosts...
baseurl: '/' # the subpath of your site, e.g. /blog
url: 'flowtrending.com'

# Build settings
defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: 'default' # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
